---
- name: Reload unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted

- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted
